// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "strings"

type PreviewMergeBarState struct {
	Active    bool
	SessionID string
	// BackURL es el destino del botón "Back to agent". Construido
	// server-side (en preview_context_ui.go) usando mounted.Host
	// para que apunte al chat del agente en el host y NO adentro
	// del mount del preview — el botón homónimo del chat usa el
	// mismo criterio via hostAgentSessionURL.
	BackURL string
	// NoChanges aplica sólo cuando Success=true. Indica que el
	// merge se ejecutó correctamente pero la rama de preview no
	// tenía commits nuevos para integrar (preview-branch == base
	// o preview totalmente mergeado en base). El bar muestra un
	// estado neutro ("Up to date") y el handler no crea sesión
	// nueva en este caso.
	NoChanges     bool
	BaseBranch    string
	PreviewBranch string
	Applicable    bool
	ActionPath    string
	ErrorMessage  string
	Success       bool
}

func PreviewMergeBar(state PreviewMergeBarState) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if !state.Active {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"global-preview-merge-bar\"></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<div id=\"global-preview-merge-bar\" class=\"fixed inset-x-0 bottom-0 z-40 border-t border-base-300/60 bg-base-100/92 backdrop-blur\"><div class=\"mx-auto flex max-w-screen-2xl items-center gap-3 px-4 py-1.5 text-xs\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 = []any{previewMergeBarBadgeClass(state)}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<span class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var2).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/layout/preview_merge_bar.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(previewMergeBarBadge(state))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/layout/preview_merge_bar.templ`, Line: 35, Col: 82}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "></span> <span class=\"flex-1 truncate text-base-content/84\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 string
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(previewMergeBarMessage(state))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/layout/preview_merge_bar.templ`, Line: 36, Col: 86}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "></span><div class=\"flex shrink-0 items-center gap-2\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if strings.TrimSpace(state.BackURL) != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<a class=\"btn btn-xs btn-ghost\" href=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var6 templ.SafeURL
				templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(state.BackURL))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/layout/preview_merge_bar.templ`, Line: 39, Col: 73}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\">Back to agent</a> ")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			if state.Applicable && strings.TrimSpace(state.ErrorMessage) == "" && !state.Success {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<button class=\"btn btn-xs btn-primary\" hx-post=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var7 string
				templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.ResolveAttributeValue(state.ActionPath)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/layout/preview_merge_bar.templ`, Line: 44, Col: 33}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var7)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\" hx-target=\"#global-preview-merge-bar\" hx-swap=\"outerHTML\" hx-confirm=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var8 string
				templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.ResolveAttributeValue(previewMergeConfirm(state))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/layout/preview_merge_bar.templ`, Line: 47, Col: 46}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var8)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "\">Merge preview</button>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</div></div></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

func previewMergeBarTone(state PreviewMergeBarState) string {
	if strings.TrimSpace(state.ErrorMessage) != "" {
		return "text-error"
	}
	if state.Success {
		if state.NoChanges {
			return "text-base-content"
		}
		return "text-success"
	}
	return "text-base-content"
}

func previewMergeBarBadgeClass(state PreviewMergeBarState) string {
	if strings.TrimSpace(state.ErrorMessage) != "" {
		return "badge badge-error badge-sm"
	}
	if state.Success && !state.NoChanges {
		return "badge badge-success badge-sm"
	}
	// success + no changes, o estado neutral (apenas cargada la
	// preview, sin click todavía): ambos usan tono info para no
	// sugerir éxito falso ni error.
	return "badge badge-info badge-sm"
}

func previewMergeBarBadge(state PreviewMergeBarState) string {
	if strings.TrimSpace(state.ErrorMessage) != "" {
		return "Blocked"
	}
	if state.Success {
		if state.NoChanges {
			return "Up to date"
		}
		return "Applied"
	}
	return "Preview"
}

func previewMergeBarMessage(state PreviewMergeBarState) string {
	if msg := strings.TrimSpace(state.ErrorMessage); msg != "" {
		return msg
	}
	if state.Success {
		if state.NoChanges {
			return "No hay cambios nuevos para mergear."
		}
		if strings.TrimSpace(state.BaseBranch) != "" {
			return "Cambios aplicados a " + state.BaseBranch + "."
		}
		return "Cambios aplicados."
	}
	return "Preview aislada: lo que veas aquí no se aplica al workspace base."
}

func previewMergeConfirm(state PreviewMergeBarState) string {
	preview := strings.TrimSpace(state.PreviewBranch)
	base := strings.TrimSpace(state.BaseBranch)
	if preview != "" && base != "" {
		return "Esto va a mergear la rama " + preview + " en " + base + " (no fast-forward). Si la preview no tiene cambios, no se creará un commit."
	}
	if preview != "" {
		return "Esto va a mergear la rama " + preview + " en el branch base (no fast-forward)."
	}
	return "Esto va a mergear la preview en el branch base."
}

var _ = templruntime.GeneratedTemplate
