// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package v2

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/microcosm-cc/bluemonday"
	"github.com/yuin/goldmark"

	agentapp "lastmile-agents/internal/agent/application"
)

// RenderItem pinta un ConversationItem como HTML. Es el mismo
// contrato que la V1 (agentui.RenderItem) pero con un HTML más
// austero: la V2 está en modo "base limpia" durante M-A — sin
// daisyUI chat-bubble, sin glass-panel, sin emojis. Cuando M-B
// entre (thinking + tools), acá se rediseña sin tocar V1.
//
// Mientras tanto: un wrapper <article> con data-msg para que el
// upsert por id funcione, y clases planas para que el CSS
// standalone las pueda estilar después.
func RenderItem(item agentapp.ConversationItem) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{itemClass(item.Kind)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div data-msg=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(itemSeq(item))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/fragments.templ`, Line: 27, Col: 30}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" data-kind=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(item.Kind)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/fragments.templ`, Line: 27, Col: 54}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/fragments.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		switch item.Kind {
		case "user":
			var templ_7745c5c3_Var6 string
			templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(item.Text)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/fragments.templ`, Line: 30, Col: 15}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case "assistant":
			templ_7745c5c3_Err = templ.Raw(assistantHTML(item.Text)).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case "thinking":
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "            <details class=\"v2-thinking\" open><summary><span class=\"v2-thinking-label\">Pensando</span> <span class=\"v2-thinking-meta\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(v2ThinkingMeta(item.Text))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/fragments.templ`, Line: 49, Col: 64}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</span></summary><pre class=\"v2-thinking-content\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(item.Text)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/fragments.templ`, Line: 51, Col: 49}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</pre></details>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case "tool":
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<div class=\"v2-tool\"><div class=\"v2-tool-name\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var9 string
			templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(toolName(item))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/fragments.templ`, Line: 55, Col: 47}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if len(item.Args) > 0 && string(item.Args) != "null" {
				templ_7745c5c3_Err = templ.Raw(formatToolArgs(item.Args)).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case "tool_result":
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "    <div class=\"v2-tool-result\"><div class=\"v2-tool-result-label\">output · ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var10 string
			templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(toolName(item))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/fragments.templ`, Line: 66, Col: 65}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</div><pre class=\"v2-tool-output\"><code>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var11 string
			templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(item.Text)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/fragments.templ`, Line: 74, Col: 50}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</code></pre></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		case "error":
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "<div class=\"v2-error-text\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var12 string
			templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(item.Text)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/fragments.templ`, Line: 77, Col: 42}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		default:
			var templ_7745c5c3_Var13 string
			templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(item.Text)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/fragments.templ`, Line: 79, Col: 15}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "<div class=\"v2-item-actions\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if item.Kind == "assistant" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "<button type=\"button\" class=\"v2-item-regenerate\" data-regenerate-button aria-label=\"Regenerar respuesta\" title=\"Regenerar respuesta\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><path d=\"M3 12a9 9 0 0 1 15.5-6.36L21 8\"></path><path d=\"M21 3v5h-5\"></path><path d=\"M21 12a9 9 0 0 1-15.5 6.36L3 16\"></path><path d=\"M3 21v-5h5\"></path></svg></button> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "<button type=\"button\" class=\"v2-item-copy\" data-copy-button aria-label=\"Copiar mensaje\" title=\"Copiar\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><rect x=\"9\" y=\"9\" width=\"13\" height=\"13\" rx=\"2\" ry=\"2\"></rect><path d=\"M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1\"></path></svg></button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// RenderToolResultItem produce el mismo HTML que un item
// tool_result, pero con un atributo adicional data-upsert-key
// que el cliente usa para reemplazar el mismo nodo DOM en cada
// update de un tool_execution_update. A diferencia de RenderItem,
// este NO usa el seq del transcript para el data-msg (porque
// el transcript no contiene los partials; sólo el END). El
// data-msg es estable (igual a la toolCallID como string) para
// que cualquier lógica de upsert por data-msg que aún no use
// UpsertKey siga funcionando.
//
// El data-upsert-key es el que el cliente prefiere usar para
// el upsert. Ambos atributos están presentes para que la
// migración sea gradual (la versión vieja del cliente sigue
// funcionando via data-msg, la nueva usa data-upsert-key).
func RenderToolResultItem(toolCallID string, toolName string, text string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var14 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var14 == nil {
			templ_7745c5c3_Var14 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "<div data-msg=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var15 string
		templ_7745c5c3_Var15, templ_7745c5c3_Err = templ.ResolveAttributeValue("tool_result:" + toolCallID)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/fragments.templ`, Line: 120, Col: 44}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var15)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "\" data-upsert-key=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var16 string
		templ_7745c5c3_Var16, templ_7745c5c3_Err = templ.ResolveAttributeValue(toolCallID)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/fragments.templ`, Line: 120, Col: 75}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var16)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "\" data-kind=\"tool_result\" class=\"v2-item v2-item-tool_result\"><div class=\"v2-tool-result\"><div class=\"v2-tool-result-label\">output · ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var17 string
		templ_7745c5c3_Var17, templ_7745c5c3_Err = templ.JoinStringErrs(toolName)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/fragments.templ`, Line: 122, Col: 57}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var17))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "</div><pre class=\"v2-tool-output\"><code>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var18 string
		templ_7745c5c3_Var18, templ_7745c5c3_Err = templ.JoinStringErrs(text)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/fragments.templ`, Line: 123, Col: 43}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var18))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "</code></pre></div><div class=\"v2-item-actions\"><button type=\"button\" class=\"v2-item-copy\" data-copy-button aria-label=\"Copiar output\" title=\"Copiar\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><rect x=\"9\" y=\"9\" width=\"13\" height=\"13\" rx=\"2\" ry=\"2\"></rect><path d=\"M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1\"></path></svg></button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// RenderMessage devuelve el HTML de un ConversationItem como
// string, listo para serializar en un envelope SSE. Lo usa el
// FragmentRenderer V2 que el handler SSE consume.
func RenderMessage(item agentapp.ConversationItem) (string, error) {
	var buf bytes.Buffer
	if err := RenderItem(item).Render(context.Background(), &buf); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func itemSeq(item agentapp.ConversationItem) string {
	if item.Seq > 0 {
		b, _ := json.Marshal(item.Seq)
		return string(b)
	}
	return item.Kind + ":" + item.Text
}

func itemClass(kind string) string {
	switch kind {
	case "user":
		return "v2-item v2-item-user"
	case "assistant":
		return "v2-item v2-item-assistant"
	case "thinking":
		return "v2-item v2-item-thinking"
	case "tool":
		return "v2-item v2-item-tool"
	case "tool_result":
		return "v2-item v2-item-tool-result"
	case "error":
		return "v2-item v2-item-error"
	default:
		return "v2-item v2-item-misc"
	}
}

func toolName(item agentapp.ConversationItem) string {
	if item.ToolName != "" {
		return item.ToolName
	}
	return "tool"
}

// ponytail: formatToolArgs convierte los args de un tool call en
// un formato legible. El "antes" era JSON.MarshalIndent, que es
// hostil para usuarios que no viven en la terminal — un tool con
// 5 keys terminaba como un bloque de JSON con corchetes y
// comillas por todas partes. El "después":
//
//   - Si args es un objeto plano con valores primitivos
//     (string, number, bool, null), se imprime key:value línea
//     por línea. Ej:
//     command: ls -la
//     timeout: 30
//     verbose: true
//
//   - Si tiene anidación, arrays u objetos anidados, cae al
//     JSON formateado (sigue siendo mejor que nada). Marcar
//     como "json" para que el usuario sepa.
//
//   - Si el JSON es inválido, lo muestra crudo con prefijo
//     "raw:" para que sea obvio.
//
//   - Si está vacío o es null, retorna string vacío.
//
// Esto NO reemplaza el highlight de syntax: los args siguen
// siendo monoespaciados. Sólo cambia el layout.
func formatToolArgs(raw json.RawMessage) string {
	trimmed := strings.TrimSpace(string(raw))
	if trimmed == "" || trimmed == "null" {
		return ""
	}
	var v any
	if err := json.Unmarshal(raw, &v); err != nil {
		// JSON inválido: mostramos crudo para que el usuario
		// pueda ver qué llegó.
		return fmt.Sprintf(`<span class="v2-tool-args-raw">raw:</span> %s`, escapeHTML(trimmed))
	}
	// Caso simple: objeto plano con primitivos → key:value.
	if obj, ok := v.(map[string]any); ok && allPrimitive(obj) {
		var b strings.Builder
		// Orden estable por nombre de key para que el output
		// sea predecible (importante para tests y para evitar
		// que el contenido "salte" entre SSE updates del mismo
		// tool).
		keys := sortedKeys(obj)
		for _, k := range keys {
			val := obj[k]
			b.WriteString(`<div class="v2-tool-arg">`)
			b.WriteString(`<span class="v2-tool-arg-key">`)
			b.WriteString(escapeHTML(k))
			b.WriteString(`</span>`)
			b.WriteString(`<span class="v2-tool-arg-sep">:</span> `)
			b.WriteString(`<span class="v2-tool-arg-val">`)
			b.WriteString(escapeHTML(formatPrimitive(val)))
			b.WriteString(`</span>`)
			b.WriteString(`</div>`)
		}
		return b.String()
	}
	// Fallback: JSON formateado.
	pretty, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		return escapeHTML(trimmed)
	}
	return fmt.Sprintf(`<span class="v2-tool-args-raw">json:</span> <pre class="v2-tool-args-fallback">%s</pre>`, escapeHTML(string(pretty)))
}

// allPrimitive devuelve true si todos los valores del objeto
// son primitivos JSON (string, number, bool, null). Usado para
// decidir si podemos formatear como key:value o tenemos que
// caer al JSON indent.
func allPrimitive(obj map[string]any) bool {
	for _, v := range obj {
		switch v.(type) {
		case string, float64, bool, nil:
			continue
		default:
			return false
		}
	}
	return true
}

// sortedKeys devuelve las keys de un objeto ordenadas
// alfabéticamente. Como las keys vienen de json.Unmarshal, ya
// tienen un orden estable, pero queremos que el output sea
// determinístico entre renders (importante para tests y para
// que el upsert por data-msg no produzca re-renders visibles).
func sortedKeys(obj map[string]any) []string {
	keys := make([]string, 0, len(obj))
	for k := range obj {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// formatPrimitive serializa un valor primitivo para mostrar en
// los args del tool. Los strings van entre comillas (estilo
// CLI), los números/bools/null se imprimen raw.
func formatPrimitive(v any) string {
	switch val := v.(type) {
	case nil:
		return "null"
	case bool:
		if val {
			return "true"
		}
		return "false"
	case float64:
		// Si es entero, sin decimal. Si tiene parte fraccional,
		// la mostramos. fmt %g da formato compacto (1234 en vez
		// de 1234.000000) sin perder precisión razonable.
		if val == float64(int64(val)) {
			return fmt.Sprintf("%d", int64(val))
		}
		return fmt.Sprintf("%g", val)
	case string:
		// Si el string tiene newlines o caracteres raros, lo
		// envolvemos en comillas. Si es una sola línea limpia,
		// también con comillas (consistencia con CLI tools).
		return fmt.Sprintf("%q", val)
	default:
		// No debería pasar si allPrimitive dio true, pero por
		// las dudas serializamos JSON.
		b, _ := json.Marshal(v)
		return string(b)
	}
}

// escapeHTML escapa los 5 caracteres peligrosos. Es la versión
// mínima necesaria para evitar XSS en valores que vamos a
// inyectar con templ.Raw (los args del tool vienen del LLM y
// pueden contener <script> u otro HTML malicioso). Diferente
// del escape de assistantHTML: acá NO queremos markdown, sólo
// texto plano entre tags <span>.
func escapeHTML(s string) string {
	r := strings.NewReplacer(
		"&", "&amp;",
		"<", "&lt;",
		">", "&gt;",
		`"`, "&quot;",
		"'", "&#39;",
	)
	return r.Replace(s)
}

// ponytail: el cliente del chat necesita markdown renderizado en
// los mensajes del assistant (code blocks con highlighting,
// negritas, itálicas, links, listas). Procesamos server-side con
// goldmark + bluemonday para mantenerlo seguro: el texto viene
// del LLM y podría contener HTML/scripts. bluemonday sanea
// dejando solo lo que el chat necesita.
//
// Lista permitida (la "StrictPolicy" no alcanza porque rompe
// links y code blocks; la "UGCPolicy" es la base estándar pero
// también bloquea <h1>-<h6>; hacemos una política a mano con
// solo lo que el chat de un agente de programación usa).
var (
	mdRenderer = goldmark.New(
		goldmark.WithExtensions(),
	)
	mdPolicy = bluemonday.NewPolicy()
)

// mdPolicy habilita las tags que el chat de un coding agent
// realmente usa: párrafos, headings, énfasis, code (inline +
// block), listas, blockquote, links seguros (sin javascript:
// ni on* handlers), tablas, hr, line breaks. Bloquea <script>,
// <style>, <iframe>, <object>, <embed>, etc. — cualquier cosa
// que pueda ejecutar código o cargar recursos externos.
func init() {
	mdPolicy.AllowElements(
		"p", "br", "hr",
		"strong", "em", "del", "s", "u",
		"code", "pre",
		"a", "ul", "ol", "li",
		"h1", "h2", "h3", "h4", "h5", "h6",
		"blockquote",
		"table", "thead", "tbody", "tr", "th", "td",
	)
	// href solo si es http/https/mailto/relative. Bloquea
	// javascript: y data: (vector histórico de XSS).
	mdPolicy.AllowAttrs("href").OnElements("a")
	mdPolicy.AllowURLSchemes("http", "https", "mailto")
	// class solo en <code> y <pre> para que el highlight
	// (lenguaje) pueda estilarse. Si en el futuro queremos
	// más, lo agregamos explícito — no abrimos la puerta a
	// class arbitraria en cualquier tag.
	mdPolicy.AllowAttrs("class").Matching(bluemonday.SpaceSeparatedTokens).OnElements("code", "pre")
}

// assistantHTML convierte el texto plano del assistant a HTML
// markdown saneado. Si el texto está vacío (después de strippear
// <think>), retorna string vacío. Si goldmark falla por
// cualquier razón (markdown malformado extremo), caemos al
// texto plano saneado — el chat sigue funcionando, sólo sin
// formato.
//
// IMPORTANTE: el output se inyecta con templ.Raw en RenderItem.
// bluemonday es la ÚNICA razón por la que esto es seguro —
// nunca reemplaces bluemonday por html.EscapeString directo,
// porque el markdown se procesa ANTES de escapar y puede
// introducir tags nuevas.
func assistantHTML(text string) string {
	clean := assistantVisibleText(text)
	if clean == "" {
		return ""
	}
	var buf bytes.Buffer
	if err := mdRenderer.Convert([]byte(clean), &buf); err != nil {
		// Fallback: texto plano saneado. El chat sigue
		// legible aunque pierda formato.
		return mdPolicy.Sanitize(clean)
	}
	return string(mdPolicy.SanitizeBytes(buf.Bytes()))
}

// assistantVisibleText strippea los bloques <think>...</think>
// del texto del assistant (defensa: por si pi los inlinea en un
// text_delta en vez de mandarlos como thinking_delta separado).
// El thinking "real" ya tiene su propio item con kind="thinking".
//
// ponytail: si el stream del LLM se corta mid-reasoning (timeout,
// navigation away, etc), el texto puede tener un <think> sin
// </think> correspondiente. El código viejo hacía text=text[:start]
// que borraba todo desde el <think> hasta el final, perdiendo
// la respuesta visible que vino después. La fix: salir del loop
// y dejar que el ReplaceAll de abajo limpie el tag huérfano. El
// usuario ve el texto restante (incluyendo razonamiento parcial
// si lo hay) en vez de perder la respuesta. El bug que motivó
// la fix: el user reportó "texto español recortado" en sesiones
// donde el stream se cortó durante un turno.
func assistantVisibleText(text string) string {
	if strings.TrimSpace(text) == "" {
		return ""
	}
	for {
		start := strings.Index(text, "<think>")
		if start < 0 {
			break
		}
		end := strings.Index(text[start+len("<think>"):], "</think>")
		if end < 0 {
			// <think> sin cierre: salimos sin chappear, el
			// ReplaceAll de abajo limpia el tag. Ver el
			// comentario de la copia en
			// internal/agent/application/assistant_text.go
			// (visibleAssistantText) para la motivación.
			break
		}
		end += start + len("<think>")
		text = text[:start] + text[end+len("</think>"):]
	}
	text = strings.ReplaceAll(text, "<think>", "")
	text = strings.ReplaceAll(text, "</think>", "")
	return strings.TrimSpace(text)
}

// v2ThinkingMeta devuelve un texto corto para el header del
// bloque colapsable de thinking. Da al usuario una idea del tamaño
// sin necesidad de expandir: corto → caracteres, largo → palabras
// + caracteres.
func v2ThinkingMeta(text string) string {
	trimmed := strings.TrimSpace(text)
	if trimmed == "" {
		return "vacío"
	}
	words := 1
	for _, r := range trimmed {
		if r == ' ' || r == '\n' || r == '\t' {
			words++
		}
	}
	if len(trimmed) < 200 {
		return fmt.Sprintf("%d caracteres", len(trimmed))
	}
	return fmt.Sprintf("%d palabras · %d caracteres", words, len(trimmed))
}

var _ = templruntime.GeneratedTemplate
