// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package v2

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"regexp"
	"strconv"
	"strings"

	agentapp "lastmile-agents/internal/agent/application"
)

// Page renderiza la shell principal del chat V2. Estructura:
//
//	<header>           → título de sesión + estado + abort + new
//	<aside>            → lista de sesiones (sidebar)
//	<main#feed>        → mensajes del chat
//	<form#composer>    → input del usuario
//
// La V2 empieza deliberadamente austera (sin daisyUI chat-bubble,
// sin glass-panel, sin emojis) porque el objetivo de M-A es
// validar el flujo base con streaming visible, no conseguir
// paridad visual con la V1. La estética entra en M-B junto con
// thinking + tool cards.
func Page(state PageState) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"v2-app\" class=\"v2-shell\" data-active-session-id=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(activeSessionID(state))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 24, Col: 82}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" data-mount-prefix=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.ResolveAttributeValue(state.MountPrefix)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 24, Col: 122}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var3)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" data-user-jwt=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.ResolveAttributeValue(state.UserJWT)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 24, Col: 154}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var4)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" data-chat-state=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.ResolveAttributeValue(v2ChatState(hasConversation(state)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 24, Col: 210}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var5)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\"><aside class=\"v2-sidebar\"><div class=\"v2-sidebar-header\"><h2 class=\"v2-sidebar-title\">Sesiones</h2><form id=\"v2-new-session\" class=\"v2-new-session-form\"><input type=\"hidden\" name=\"title\" value=\"Nueva sesión\"> <input type=\"hidden\" name=\"cwd\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.ResolveAttributeValue(state.DefaultCWD)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 30, Col: 61}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var6)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "\"> <input type=\"hidden\" name=\"model\" value=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.ResolveAttributeValue(state.DefaultModel)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 31, Col: 65}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var7)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\"> <button type=\"submit\" class=\"v2-btn-icon\" title=\"Nueva sesión\" aria-label=\"Nueva sesión\">+</button></form></div><ul id=\"v2-sessions-list\" class=\"v2-sessions-list\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if len(state.Sessions) == 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<li class=\"v2-sessions-empty\">Todavía no hay conversaciones.</li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		for _, session := range state.Sessions {
			var templ_7745c5c3_Var8 = []any{v2SessionRowClass(state, session.ID)}
			templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var8...)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "<li class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var9 string
			templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.ResolveAttributeValue(templ.CSSClasses(templ_7745c5c3_Var8).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var9)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\"><a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var10 templ.SafeURL
			templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinURLErrs(appPath(state, "/agent?session="+session.ID))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 41, Col: 60}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "\" class=\"v2-session-link\"><div class=\"v2-session-title\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var11 string
			templ_7745c5c3_Var11, templ_7745c5c3_Err = templ.JoinStringErrs(sessionTitle(session.Title))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 42, Col: 66}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var11))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</div><div class=\"v2-session-meta\"><span>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var12 string
			templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(sessionStatusText(session.Status))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 44, Col: 49}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</span> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if strings.TrimSpace(session.Model) != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "<span class=\"v2-session-model\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var13 string
				templ_7745c5c3_Var13, templ_7745c5c3_Err = templ.JoinStringErrs(session.Model)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 46, Col: 55}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var13))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "</span>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if sessionPreviewText(session.LastPreview) != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "<div class=\"v2-session-preview\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var14 string
				templ_7745c5c3_Var14, templ_7745c5c3_Err = templ.JoinStringErrs(sessionPreviewText(session.LastPreview))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 64, Col: 81}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var14))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "</div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "</a> <button type=\"button\" class=\"v2-btn-icon v2-session-delete\" title=\"Eliminar sesión\" data-session-delete=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var15 string
			templ_7745c5c3_Var15, templ_7745c5c3_Err = templ.ResolveAttributeValue(session.ID)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 67, Col: 123}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var15)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "\" aria-label=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var16 string
			templ_7745c5c3_Var16, templ_7745c5c3_Err = templ.ResolveAttributeValue("Eliminar sesión " + sessionTitle(session.Title))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 67, Col: 188}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var16)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "\">×</button></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "</ul></aside><main class=\"v2-main\"><header class=\"v2-header\"><button id=\"v2-sidebar-open\" class=\"v2-sidebar-open\" type=\"button\" aria-label=\"Abrir menú de sesiones\" aria-controls=\"v2-sidebar\" aria-expanded=\"false\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><line x1=\"3\" y1=\"6\" x2=\"21\" y2=\"6\"></line><line x1=\"3\" y1=\"12\" x2=\"21\" y2=\"12\"></line><line x1=\"3\" y1=\"18\" x2=\"21\" y2=\"18\"></line></svg></button><h1 class=\"v2-title\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var17 string
		templ_7745c5c3_Var17, templ_7745c5c3_Err = templ.JoinStringErrs(shellTitle(state))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 78, Col: 44}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var17))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "</h1><div class=\"v2-header-actions\"><span id=\"v2-phase-detail-badge\" class=\"v2-phase-detail-badge\" data-subphase=\"idle\" aria-live=\"polite\" aria-atomic=\"true\" hidden></span> <button id=\"v2-phase-detail-toggle\" class=\"v2-phase-detail-toggle\" type=\"button\" aria-label=\"Mostrar detalles de la actividad del agente\" aria-pressed=\"false\" title=\"Mostrar/ocultar detalle de fase\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><circle cx=\"12\" cy=\"12\" r=\"9\"></circle><path d=\"M12 8h.01M11 12h1v4h1\"></path></svg></button><a id=\"v2-preview-open\" class=\"v2-phase-detail-toggle\" href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var18 templ.SafeURL
		templ_7745c5c3_Var18, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL(shellPreviewPath(state)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 93, Col: 105}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var18))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, "\" target=\"_blank\" rel=\"noopener noreferrer\" title=\"Abrir preview en nueva tab\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if shellPreviewPath(state) == "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, " hidden")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, "><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M13.5 6H5.25A2.25 2.25 0 0 0 3 8.25v10.5A2.25 2.25 0 0 0 5.25 21h10.5A2.25 2.25 0 0 0 18 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25\"></path></svg></a><button id=\"v2-worktree-toggle\" class=\"v2-phase-detail-toggle\" type=\"button\" aria-label=\"Mostrar panel de worktree\" aria-pressed=\"false\" title=\"Mostrar/ocultar worktree inspector\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><line x1=\"6\" y1=\"3\" x2=\"6\" y2=\"15\"></line><circle cx=\"18\" cy=\"6\" r=\"3\"></circle><circle cx=\"6\" cy=\"18\" r=\"3\"></circle><path d=\"M18 9a9 9 0 0 1-9 9\"></path></svg></button> <button id=\"v2-abort\" class=\"v2-btn v2-btn-danger\" type=\"button\" hidden>Abortar</button></div></header><button id=\"v2-sidebar-backdrop\" class=\"v2-sidebar-backdrop\" type=\"button\" aria-label=\"Cerrar menú de sesiones\" tabindex=\"-1\"></button><div class=\"v2-feed-and-panel\"><section id=\"v2-feed-wrap\" class=\"v2-feed-wrap\"><div id=\"v2-feed\" class=\"v2-feed\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !hasConversation(state) {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 27, "<div class=\"v2-empty\"><p class=\"v2-empty-headline\">Mandá un mensaje para arrancar.</p><p class=\"v2-empty-sub\">El stream del assistant va a aparecer acá en vivo.</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		for _, item := range state.ConversationItems {
			templ_7745c5c3_Err = RenderItem(item).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 28, "</div><button id=\"v2-jump-bottom\" class=\"v2-jump-bottom\" type=\"button\" aria-label=\"Bajar al último mensaje\" title=\"Bajar al último mensaje\" hidden><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" aria-hidden=\"true\"><polyline points=\"6 9 12 15 18 9\"></polyline></svg> <span id=\"v2-jump-bottom-count\" class=\"v2-jump-bottom-count\"></span></button></section><aside id=\"v2-worktree-panel\" class=\"v2-worktree-panel\" aria-label=\"Worktree inspector\" hidden><header class=\"v2-worktree-header\"><h3 class=\"v2-worktree-title\">Worktree</h3><button id=\"v2-worktree-close\" type=\"button\" class=\"v2-worktree-close\" aria-label=\"Cerrar panel de worktree\" title=\"Cerrar panel\">×</button></header><div class=\"v2-worktree-body\"><section class=\"v2-worktree-section\"><h4 class=\"v2-worktree-section-title\">Branch</h4><div id=\"v2-worktree-branch-info\" class=\"v2-worktree-meta\">—</div></section><section class=\"v2-worktree-section\"><h4 class=\"v2-worktree-section-title\">Files changed <span id=\"v2-worktree-files-count\" class=\"v2-worktree-section-meta\"></span></h4><ul id=\"v2-worktree-files\" class=\"v2-worktree-list\"></ul></section><section class=\"v2-worktree-section\"><h4 class=\"v2-worktree-section-title\">Commits <span id=\"v2-worktree-commits-count\" class=\"v2-worktree-section-meta\"></span></h4><ul id=\"v2-worktree-commits\" class=\"v2-worktree-list\"></ul></section><div class=\"v2-worktree-actions\"><button id=\"v2-worktree-apply\" type=\"button\" class=\"v2-worktree-apply\" disabled title=\"Merge del worktree a la rama principal\">Aplicar a ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var19 string
		templ_7745c5c3_Var19, templ_7745c5c3_Err = templ.JoinStringErrs(v2WorktreeBaseBranch(state))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 175, Col: 46}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var19))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 29, "</button></div><div id=\"v2-worktree-apply-status\" class=\"v2-worktree-apply-status\" hidden></div><div id=\"v2-worktree-diff\" class=\"v2-worktree-diff\" hidden><pre id=\"v2-worktree-diff-content\" class=\"v2-worktree-diff-content\"></pre></div></div></aside></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = v2BudgetBar(state).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 30, "<form id=\"v2-composer\" class=\"v2-composer\" autocomplete=\"off\"><textarea id=\"v2-input\" name=\"message\" class=\"v2-input\" placeholder=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var20 string
		templ_7745c5c3_Var20, templ_7745c5c3_Err = templ.ResolveAttributeValue(v2ComposerPlaceholder(activeSessionID(state)))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 193, Col: 64}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var20)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 31, "\" rows=\"1\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if activeSessionID(state) == "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 32, " disabled")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 33, "></textarea><div class=\"v2-composer-actions\"><span class=\"v2-composer-meta\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var21 string
		templ_7745c5c3_Var21, templ_7745c5c3_Err = templ.JoinStringErrs(shellModel(state))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 200, Col: 55}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var21))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 34, "</span> <button id=\"v2-send\" type=\"submit\" class=\"v2-btn v2-btn-primary\" disabled>Enviar</button></div></form></main></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// sessionTitle devuelve el título saneado (trim + fallback).
func sessionTitle(title string) string {
	title = strings.TrimSpace(title)
	if title == "" {
		return "Nueva sesión"
	}
	return title
}

// sessionStatusText devuelve el texto del badge de estado.
func sessionStatusText(status agentapp.SessionStatus) string {
	text := strings.TrimSpace(string(status))
	if text == "" {
		return "idle"
	}
	return text
}

// sessionPreviewText devuelve un preview corto del último
// mensaje del assistant para mostrar en el sidebar. Si no hay
// preview, retorna string vacío (la UI lo esconde).
//
// El server trunca el texto a 600 caracteres en LastPreview
// (ver application/manager.go:setSessionPreview). Acá lo
// truncamos a ~80 chars para que entre en una línea del sidebar
// sin romper el layout. Si el preview empieza con tags de
// thinking (<think>...</think>) los removemos — el sidebar no
// debería mostrar razonamiento crudo.
func sessionPreviewText(preview string) string {
	clean := strings.TrimSpace(preview)
	if clean == "" {
		return ""
	}
	// ponytail: strip <think>...</think> que pi podría haber
	// dejado inline en el text_delta. Regex non-greedy para
	// tags anidados (pi a veces los emite recursivos cuando
	// re-razona sobre su propia salida).
	thinkRE := regexp.MustCompile(`<think>.*?</think>`)
	clean = thinkRE.ReplaceAllString(clean, "")
	// Si quedó un <think> sin cierre (regex no lo matchea),
	// cortamos desde ahí — el resto es reasoning que no debería
	// aparecer en el sidebar.
	if idx := strings.Index(clean, "<think>"); idx >= 0 {
		clean = clean[:idx]
	}
	// ponytail: normalizamos whitespace. El preview puede
	// tener newlines del text_delta del LLM — para una sola
	// línea en el sidebar, los colapsamos a espacios.
	clean = strings.Join(strings.Fields(clean), " ")
	clean = strings.TrimSpace(clean)
	if clean == "" {
		return ""
	}
	const max = 80
	runes := []rune(clean)
	if len(runes) > max {
		return strings.TrimSpace(string(runes[:max-1])) + "…"
	}
	return clean
}

func v2SessionRowClass(state PageState, id string) string {
	if strings.TrimSpace(activeSessionID(state)) == strings.TrimSpace(id) {
		return "v2-session-row v2-session-row-active"
	}
	return "v2-session-row"
}

func v2ChatState(hasConversation bool) string {
	if hasConversation {
		return "conversation"
	}
	return "empty"
}

func v2ComposerPlaceholder(sessionID string) string {
	if strings.TrimSpace(sessionID) == "" {
		return "Carga o crea una sesión para empezar…"
	}
	return "Escribe un mensaje. Enter envía, Shift+Enter nueva línea."
}

// v2BudgetBar renderiza la barra de presupuesto sobre el composer.
// Misma información que la V1 (balance global + gasto de la sesión
// + request count) pero en formato V2: layout horizontal compacto,
// tokens JetBrains Mono, coloreado por umbral.
//
// Los valores iniciales vienen del server-rendered snapshot en
// PageState (state.SessionCostUSD/Ready/Reqs + state.BalanceUSD).
// El módulo JS budget.js los refresca cada 15s (cost) y 60s
// (balance). Si el snapshot es nil/empty, la barra arranca con
// "—" y el cliente hace el primer poll al boot.
func v2BudgetBar(state PageState) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var22 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var22 == nil {
			templ_7745c5c3_Var22 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 35, "<div id=\"v2-budget-bar\" class=\"v2-budget-bar\" data-state=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var23 string
		templ_7745c5c3_Var23, templ_7745c5c3_Err = templ.ResolveAttributeValue(v2BudgetState(state))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 301, Col: 80}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var23)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 36, "\"><div class=\"v2-budget-cell\"><span class=\"v2-budget-label\">balance</span> <span id=\"v2-balance\" class=\"v2-budget-value\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var24 string
		templ_7745c5c3_Var24, templ_7745c5c3_Err = templ.JoinStringErrs(v2BalanceText(state))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 304, Col: 71}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var24))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 37, "</span></div><span id=\"v2-phase-badge\" class=\"v2-phase-badge\" data-state=\"idle\" aria-live=\"polite\" aria-atomic=\"true\"><span class=\"v2-phase-badge-text\"></span> <span class=\"v2-phase-badge-dots\" aria-hidden=\"true\"><span class=\"v2-working-dot\"></span> <span class=\"v2-working-dot\"></span> <span class=\"v2-working-dot\"></span></span></span>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if state.SessionModelAlias != "" || state.SessionContextWindow > 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 38, "<span class=\"v2-budget-sep\">·</span> <span id=\"v2-session-model\" class=\"v2-budget-model\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var25 string
			templ_7745c5c3_Var25, templ_7745c5c3_Err = templ.JoinStringErrs(v2SessionModelText(state))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 338, Col: 82}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var25))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 39, "</span> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if state.SessionContextWindow > 0 {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 40, "<span class=\"v2-budget-sep\">·</span> <span id=\"v2-context-pct\" class=\"v2-budget-context\" data-state=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var26 string
				templ_7745c5c3_Var26, templ_7745c5c3_Err = templ.ResolveAttributeValue(v2ContextState(state))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 341, Col: 90}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var26)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 41, "\" title=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var27 string
				templ_7745c5c3_Var27, templ_7745c5c3_Err = templ.ResolveAttributeValue(v2ContextTooltip(state))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 341, Col: 124}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var27)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 42, "\">")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var28 string
				templ_7745c5c3_Var28, templ_7745c5c3_Err = templ.JoinStringErrs(v2ContextText(state))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 341, Col: 149}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var28))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 43, "</span>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 44, "<div class=\"v2-budget-cell v2-budget-cell-spacer\"></div><div class=\"v2-budget-cell\"><span class=\"v2-budget-label\">esta sesión</span> <span id=\"v2-session-spent\" class=\"v2-budget-value\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var29 string
		templ_7745c5c3_Var29, templ_7745c5c3_Err = templ.JoinStringErrs(v2SessionSpentText(state))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 347, Col: 82}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var29))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 45, "</span> <span class=\"v2-budget-sep\">·</span> <span id=\"v2-session-requests\" class=\"v2-budget-meta\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var30 string
		templ_7745c5c3_Var30, templ_7745c5c3_Err = templ.JoinStringErrs(v2SessionRequestsText(state))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/agent/ui/v2/page.templ`, Line: 349, Col: 87}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var30))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 46, "</span></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// v2BalanceText devuelve el texto del balance global. Si el
// snapshot no llegó (gateway caído), muestra "—".
func v2BalanceText(state PageState) string {
	if state.BalanceUSD == nil {
		return "—"
	}
	return v2FormatUSD(*state.BalanceUSD)
}

// v2SessionSpentText devuelve el texto del gasto de la sesión
// activa. Si el gateway no devolvió datos, muestra "—".
func v2SessionSpentText(state PageState) string {
	if !state.SessionCostReady {
		return "—"
	}
	return v2FormatUSD(state.SessionCostUSD)
}

// v2SessionRequestsText devuelve el contador de requests formateado.
func v2SessionRequestsText(state PageState) string {
	if !state.SessionCostReady {
		return "0 req"
	}
	return v2FormatInt(int64(state.SessionCostReqs)) + " req"
}

// v2BudgetState replica la lógica de V1: si ninguna lectura
// llegó, "empty"; si todo OK, "ok". El cliente agrega los
// estados "warning"/"error" via data-state cuando el % consumido
// pasa los umbrales.
func v2BudgetState(state PageState) string {
	if state.BalanceUSD == nil && !state.SessionCostReady {
		return "empty"
	}
	return "ok"
}

// ponytail: helpers para el badge del modelo + uso del contexto.
// El badge del modelo es el model_alias devuelto por el gateway
// (ej. "minimax/m3"). El % de contexto es el total_tokens
// dividido por el context_window, con colores que cambian según
// umbrales (verde < 50%, amarillo 50-80%, rojo > 80%).
func v2SessionModelText(state PageState) string {
	return state.SessionModelAlias
}

// ponytail: v2WorktreeBaseBranch devuelve la base branch default
// para mostrar en el botón "Aplicar a X". Usado en el panel del
// worktree. Si la sesión activa tiene una base branch custom, la
// usamos; sino caemos a "main".
func v2WorktreeBaseBranch(state PageState) string {
	if state.ActiveSession != nil && strings.TrimSpace(state.ActiveSession.BaseBranch) != "" {
		return state.ActiveSession.BaseBranch
	}
	return "main"
}

// v2ContextText devuelve "19k/1M (2%)" o "—" si no hay datos.
// Formato compacto estilo pi CLI: el context_window en M (mega)
// si es >= 1M, en k si es >= 1k, sin sufijo si es < 1k.
func v2ContextText(state PageState) string {
	if state.SessionContextWindow <= 0 {
		return "—"
	}
	window := state.SessionContextWindow
	tokens := state.SessionCurrentPromptTokens
	if tokens <= 0 {
		// ponytail: fallback defensivo. Si el gateway no devuelve
		// current_prompt_tokens (versión vieja), usamos el
		// promedio (prompt_tokens / request_count). Nunca
		// mostramos el total acumulado porque distorsionaba el %
		// (ej. 60% cuando el context real era 3%).
		if state.RequestCountProxy() > 0 {
			tokens = state.SessionPromptTokens / int64(state.RequestCountProxy())
		} else {
			tokens = state.SessionPromptTokens
		}
	}
	pct := 0
	if window > 0 {
		pct = int(float64(tokens) / float64(window) * 100)
	}
	if pct < 0 {
		pct = 0
	}
	if pct > 100 {
		pct = 100
	}
	return formatTokensCompact(tokens) + "/" + formatTokensCompact(window) + " (" + v2FormatInt(int64(pct)) + "%)"
}

// v2ContextState devuelve "ok" (< 50%), "warning" (50-80%) o
// "error" (> 80%). Se aplica como data-state al span del %.
func v2ContextState(state PageState) string {
	if state.SessionContextWindow <= 0 {
		return "ok"
	}
	var pct float64
	if state.SessionCurrentPromptTokens > 0 {
		pct = float64(state.SessionCurrentPromptTokens) / float64(state.SessionContextWindow) * 100
	} else if state.RequestCountProxy() > 0 {
		// ponytail: fallback al promedio mientras el gateway no
		// devuelva current_prompt_tokens. Nunca usamos
		// SessionTotalTokens (acumulado) porque daba 60%+ cuando
		// el context real era <5%.
		avg := state.SessionPromptTokens / int64(state.RequestCountProxy())
		pct = float64(avg) / float64(state.SessionContextWindow) * 100
	}
	if pct >= 80 {
		return "error"
	}
	if pct >= 50 {
		return "warning"
	}
	return "ok"
}

// v2ContextTooltip devuelve un texto detallado para el tooltip
// del % de contexto: prompt vs completion tokens. Útil para
// debugging ("por qué el contexto está al 80%?").
func v2ContextTooltip(state PageState) string {
	if state.SessionContextWindow <= 0 {
		return ""
	}
	// ponytail: mostramos el current_prompt_tokens (última
	// llamada) en vez del acumulado, para que el tooltip
	// refleje el state real del context window.
	prompt := state.SessionCurrentPromptTokens
	if prompt <= 0 && state.RequestCountProxy() > 0 {
		prompt = state.SessionPromptTokens / int64(state.RequestCountProxy())
	}
	return "prompt: " + v2FormatInt(prompt) + " · completion: " + v2FormatInt(state.SessionCompletionTokens)
}

// formatTokensCompact formatea un número de tokens de forma
// compacta. < 1000 → "847", >= 1000 < 1M → "19k", >= 1M → "1.0M".
func formatTokensCompact(n int64) string {
	if n < 1000 {
		return v2FormatInt(n)
	}
	if n < 1_000_000 {
		// Mostrar "19k" sin decimales si es múltiplo de 1000.
		k := float64(n) / 1000
		if n%1000 == 0 {
			return v2FormatInt(n/1000) + "k"
		}
		return strings.TrimRight(strings.TrimRight(strconv.FormatFloat(k, 'f', 1, 64), "0"), ".") + "k"
	}
	m := float64(n) / 1_000_000
	return strings.TrimRight(strings.TrimRight(strconv.FormatFloat(m, 'f', 1, 64), "0"), ".") + "M"
}

// v2FormatUSD formatea un número como USD. < 0.01 → 4 decimales
// (para que el costo real no aparezca como $0.00).
func v2FormatUSD(value float64) string {
	if value == 0 {
		return "$0.00"
	}
	if value < 0.01 {
		return v2FormatFloat(value, 4)
	}
	return v2FormatFloat(value, 2)
}

func v2FormatFloat(value float64, decimals int) string {
	if decimals == 0 {
		return v2FormatInt(int64(value))
	}
	// Format manual sin importar "strconv" para mantener el archivo
	// chico. Suficiente para los valores que vemos en el chat
	// (siempre positivos, < 1M USD).
	whole := int64(value)
	frac := value - float64(whole)
	if frac < 0 {
		frac = -frac
	}
	multiplier := 1.0
	for i := 0; i < decimals; i++ {
		multiplier *= 10
	}
	fracInt := int64(frac*multiplier + 0.5)
	if fracInt >= int64(multiplier) {
		whole++
		fracInt -= int64(multiplier)
	}
	pad := ""
	padLen := decimals - len(v2FormatInt(fracInt))
	for i := 0; i < padLen; i++ {
		pad += "0"
	}
	return "$" + v2FormatInt(whole) + "." + pad + v2FormatInt(fracInt)
}

func v2FormatInt(value int64) string {
	if value == 0 {
		return "0"
	}
	negative := value < 0
	if negative {
		value = -value
	}
	digits := ""
	for value > 0 {
		digits = string(rune('0'+value%10)) + digits
		value /= 10
	}
	if negative {
		return "-" + digits
	}
	return digits
}

func v2FormatIntFromInt(value int) string {
	return v2FormatInt(int64(value))
}

var _ = templruntime.GeneratedTemplate
